### ISSUE TITLE
Icons on map

### ISSUE THREAD

**Issue by hartcr17** [AliKayahan/nhsmeeting#40]
_Scenario: Viewing building details on meeting location page_
-	Given that I access the meeting page
-	When I view the map of a meeting
-	And press the location icon
-	Then a pop-up of the building of the meeting should appear
-	And should show address details, pictures and directions to the location

_Scenario: Viewing attendee details on meeting location page_
-	Given that I access the meeting page
-	When I view the map of a meeting
-	And press the profile picture of a colleague on the map
-	Then a pop-up the colleague will appear on the screen
-	And it will show meetings that he/she is due to attend

**Comment by AliKayahan** [comment]
Completed
